spring:
  datasource:
    url: jdbc:h2:mem:secure_share_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
file:
  upload-dir: src/main/resources/uploads