spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  link:
    expiry-minutes: 30
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000