spring:
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  link:
    expiry-minutes: 30
jwt:
  secret: your-default-secret-key
  expiration: 86400000
